export { createAuthoringClient, type AuthoringClient, type InspectPuppetRequest, type NormalizeRigProjectRequest } from './client.js';

export type {
  BuildRigArtifactPaths,
  BuildRigProjectRequest,
  BuildRigProjectResult,
  CreatePuppetRequest,
  CreatePuppetResult,
  EditPuppetRequest,
  EditPuppetResult,
  EvaluateParameterValuesOptions,
  ParameterEvaluationResult,
  PreviewFrameMetadata,
  PreviewParameterValues,
  RigProjectDiagnostic,
  RigProjectInspection,
  RigProjectLayer,
  RigProjectManifest,
  RigProjectMotionIntent,
  PuppetEditOperation,
  PuppetInspection,
  RenderPreviewRequest,
  SavePuppetRequest,
  SavePuppetResult,
} from '@inochi-agent-tools/core';
