import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';

const output = path.join(process.cwd(), 'tests', 'fixtures', 'generated', 'm2-checker.png');
// Genuine deterministic 2x2 RGBA PNG: red, green, blue, white pixels.
// Source authority is this known-good PNG payload; generated bytes stay ignored.
const pngBase64 = 'iVBORw0KGgoAAAANSUhEUgAAAAIAAAACCAYAAABytg0kAAAAGUlEQVR4nAXBAQ0AAAzDIJbcv+UeRNJNwgM+/wYAhdCTnAAAAABJRU5ErkJggg==';
const expectedSignature = Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]);

mkdirSync(path.dirname(output), { recursive: true });
writeFileSync(output, Buffer.from(pngBase64, 'base64'));
const bytes = readFileSync(output);
if (bytes.length <= expectedSignature.length || !bytes.subarray(0, expectedSignature.length).equals(expectedSignature)) {
  throw new Error('generated M2 fixture is not a valid PNG container');
}
console.log(output);
