import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';

const output = path.join(process.cwd(), 'tests', 'fixtures', 'generated', 'm2-checker.png');
// Genuine 2x2 RGBA PNG. The fixture is deterministic and source authority is this constant, not generated bytes.
const pngBase64 = 'iVBORw0KGgoAAAANSUhEUgAAAAIAAAACCAYAAABytg0kAAAAFElEQVR4nGP4z8Dwn4GBgYGJAQoAHgQCAfM7WfQAAAAASUVORK5CYII=';
const expectedSignature = Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]);

mkdirSync(path.dirname(output), { recursive: true });
writeFileSync(output, Buffer.from(pngBase64, 'base64'));
const bytes = readFileSync(output);
if (bytes.length <= expectedSignature.length || !bytes.subarray(0, expectedSignature.length).equals(expectedSignature)) {
  throw new Error('generated M2 fixture is not a valid PNG container');
}
console.log(output);
